name: FCCommands
main: biz.itechsolutions.bukkitplugin.FCCommands.FCCommands
version: 0.0.1

commands:
  fcc:
    description: Main command for FCCommands.
    permission: fccommands.fcc
    usage: /fcc bleh - Does nothing
