name: FCCommands
main: biz.itechsolutions.bukkitplugin.FCCommands.FCCommands
version: 0.0.1

commands:
  fccommands:
    description: Main command for FCCommands.
    permission: fccommands.fccommands
    usage: /fccommands bleh - Does nothing
